[build]
  command = "NODE_ENV=development npm ci && NODE_ENV=production npm run build"
  publish = "dist"
  base = "/"

[build.environment]
  NODE_VERSION = "20"
  NPM_VERSION = "10"
  CI = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 