[build]
  command = "npm run build"
  publish = "dist"
  base = "/"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--no-audit --no-optional"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 