[build]
  command = "NODE_ENV=development npm ci && NODE_ENV=production npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"
  NPM_VERSION = "10"
  CI = "false"
  NETLIFY_SKIP_PLUGIN_INSTALL = "true"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 